[package]
name = "nscope-nodejs"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nscope = { git = "https://github.com/nLabs-nScope/nscope-rs", rev = "10346dd30797421d2179d87e7dfa82135adfc756" }
env_logger = "0.10.1"
log = "~0.4"
neon = "~1.0.0"
