[package]
name = "nlab-nodejs"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nlabapi = { git = "https://github.com/nLabs-nScope/nlabapi", branch = "main" }
env_logger = "0.10.1"
log = "~0.4"
neon = "~1.0.0"
