name: nScope Packaging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            target_architecture: x64
            executable_path: xvfb-run out/nScope-linux-x64/nScope
            artifact_path: out/make/deb/x64/nscope_*.deb
          - os: macos-latest
            target_architecture: universal
            executable_path: out/nScope-darwin-universal/nScope.app/Contents/MacOS/nScope
            artifact_path: 'out/make/nScope Installer.dmg'
          - os: windows-latest
            target_architecture: x64
            executable_path: out/nScope-win32-x64/nScope.exe
            artifact_path: 'out/make/squirrel.windows/x64/nScope Installer.exe'
            shell: cmd
    name: ${{ matrix.target_architecture }} on ${{ matrix.os }}
    steps:
      - name: Install Rust Toolchains
        if: matrix.os == 'macos-latest'
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
      - name: Install libusb
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libusb-1.0-0-dev libudev-dev
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install NPM Dependencies
        run: npm ci
      - name: Add MacOS certs
        if: matrix.os == 'macos-latest'
        run: chmod +x add-osx-cert.sh && ./add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.TEST_DEV_CERT }}
          CERTIFICATE_PASSWORD: ${{ secrets.TEST_DEV_CERT_PW }}
      - name: Build nScope
        run: npm run build
      - name: Package
        run: npm run make -- --arch ${{ matrix.target_architecture }}
        env:
          DEBUG: "electron-packager"
      - name: Smoke Test
        run: ${{ matrix.executable_path }}
        env:
          NSCOPE_SMOKE_TEST: 1
      - name: Archive the distributable
        uses: actions/upload-artifact@v3
        with:
          name: nScope Installers
          path: ${{ matrix.artifact_path }}
