name: nScope Packaging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 18
        node_architecture:
          - x64
        include:
          - os: ubuntu-latest
            artifact_path: out/make/deb/x64/nscope_*.deb
            target_architecture: x64
          - os: macos-latest
            artifact_path: out/make/nScope*.dmg
            target_architecture: universal
          - os: windows-latest
            artifact_path: out/make/squirrel.windows/x64/nScope*Setup.exe
            target_architecture: x64
    name: ${{ matrix.target_architecture }} on ${{ matrix.os }}
    steps:
      - name: Install libusb
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libusb-1.0-0-dev libudev-dev
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.node_architecture }}
      - name: Install NPM Dependencies
        run: npm ci
      - name: Build nScope
        run: npm run build
      - name: Package
        run: npm run make -- --arch ${{ matrix.target_architecture }}
      - name: Archive the distributable
        uses: actions/upload-artifact@v3
        with:
          name: nScope Installers
          path: ${{ matrix.artifact_path }}
